### ISSUE TITLE
Is there any way to export a subfolder as a file?

### ISSUE THREAD

**Issue by gbava** [hunyadi/md2conf#26]
Hello, first of all thanks for this great work.
Is there any way to export a subfolder as a file? 
When I export a subfolder that contains some .md files they are being exported to the root page id (the one defined by the argument: -r $page_id) so there´s no way to have child pages like the ones used in Confluence.
Any workaround for this?

Thank you!

**Comment by hunyadi** [comment]
That's strange. Can you share some context, specifically, a minimal set of steps to reproduce the issue? When a Markdown file to be exported has no Confluence page ID associated with it via Markdown comments, the function `get_or_create_page` would look up the page ID based on the page title, and if no match is found, invoke the function `create_page` to create a child page under the root page (set with `-r`). However, from what you write, it seems as if this feature is not working as expected under some circumstances.

**Comment by pavelkestefran** [comment]
Hello everyone 👋  

I believe this issue is about creating hierarchies deeper than just one common ancestor provided by `-r`

This is something that is not supported as per my brief checks.

---- 

Currently it doesn't matter what is the structure of the directory containing md files. 

See screenshot below `sample/childpages` 

![Screenshot 2024-02-19 at 22 51 34](https://github.com/hunyadi/md2conf/assets/18596276/8ce6c1fb-d71a-4e28-84ab-7d050e8e5282)

After running
```
python3 -m md2conf -p "/" -d confluence.example.com -s "SPACE" -r "406278878" sample/childpages/
```

the produced confluence pages hierarchy is flat under common ancerstor 

![Screenshot 2024-02-19 at 22 50 55](https://github.com/hunyadi/md2conf/assets/18596276/befb9f19-bf6d-490e-b1ea-3aef6fe0a1a5)

rather than something like this

![Screenshot 2024-02-19 at 22 52 20](https://github.com/hunyadi/md2conf/assets/18596276/f6ab91db-450b-4fed-a8c3-7fabd622c555)

**Comment by hunyadi** [comment]
The switch `-r` (root page) is a contributed feature. I have tested it with a couple of examples, and the code looked OK. However, if we proceed top to bottom, creating the topmost page first, I believe the implementation could be extended to tackle directory hierarchies.

**Comment by ojacques** [comment]
Note: there is an in-progress fix in the `dev` branch.

**Comment by hemstreet** [comment]
Are there any plans on getting this merged into the master branch? I'd like to create a folder hierarchy w/ my docs. 

The work I did around the [docker containers](https://github.com/hunyadi/md2conf/pull/51) ( since it copies the files into the container ) does not update the page_id metadata so it will always use `get_or_create_page` function. 

This would be a great feature to have, although then we lose out on some of the newer features in the past ~4 months like kroki support.

**Comment by hunyadi** [comment]
Yes. Unfortunately, the branch `dev` (as it stands) is a mix of two contributions:
1. handling directory hierarchies, which I believe to be an important feature, and
2. automatic creation of pages based on title, in which name conflicts are resolved by appending hidden spaces.

Personally, I consider the second to pose risk (e.g. non-deterministic behavior, tricky names that confuse users), and would want to remove from the contributed code. Much to my dismay, I have not yet had the time. Once the contributed code is boiled down to synchronizing directory hierarchies, I can merge to `master`.

**Comment by hemstreet** [comment]
Personally, I find that #1 is a crucial feature that, without it, is making me consider / explore other options.

#2 solution may be a nice to have but i'd gladly go without that feature, Confluence set the limitation. 

The use case I see in my brain for #2 is, in my case, is having multiple repos having their documentation split out into each respective repo yet publish to the same confluence space as one cohesive wiki. It would be frustrating to have Repo A and Repo B both have a file called `architecture.md`. When the docs get published via CI, they would be overwriting each other without really knowing and have some really odd behavior due to `get_or_create_page`.

**Comment by ojacques** [comment]
I am not in front of my dev environment, but I am happy to untangle 1 and 2, so that 1 can make it to main. For 2, I still need to find a longer term solution. 

I was planning to continue to work on md2conf so that it fully works for my case, but that work got paused for a while.
@hemstreet  - you could use the dev branch as is for now, unless you have a blocker which does not allow you to do so?

**Comment by hemstreet** [comment]
Yeah I could setup the dev branch to get that feature. That's a good point! I was hoping to use the new, shiny Kroki feature. I might give that a shot depending on how long you are thinking that might take. I'd take folder hierarchy over Kroki though.

My PR ( hopefully that will be merged soon ) builds a docker image and publishes. So hopefully that is the start of a public official docker image. 

Public image would make my life easier. For work, I have an internal docker feed i'd have to build and publish the dev branch to so it isn't the worst.

@hunyadi - This makes me think of another part of my PR, will this dev branch be long lived? If so, should there be a pipeline to publish a new python package / docker image for dev? I guess at that point it would be "beta" for people ( like me ) in this situation that understand that it's a dev/beta branch but want to use/test features like this?

**Comment by manugarri** [comment]
@hunyadi is this issue fixed? I see this pr https://github.com/hunyadi/md2conf/pull/34 that claims to have solved this issue, however, with the latest release at the moment (0.1.13) the issue still remains.

**Comment by hunyadi** [comment]
[Add support for directory structures](https://github.com/hunyadi/md2conf/pull/34) is available on the branch `dev` but not yet merged to `master` (or available in any of the published releases). I am planning a new release 0.2.0 from the branch `master` in the next few days but this is not yet going to include changes from `dev` as we have [some points](https://github.com/hunyadi/md2conf/issues/26#issuecomment-2341875458) to iron out. However, I consider exporting directory structures as an important feature, and will do my best to get it to `master` as soon as possible (without introducing regressions).

**Comment by manugarri** [comment]
awesome, looking forward to the release!

**Comment by hunyadi** [comment]
A proposed solution has been pushed to `master`. The approach uses `index.md` or `README.md` (whichever is present) to obtain a parent page ID, and all pages in a directory that don't have an explicit page ID are created with the corresponding Confluence page of `index.md` or `README.md` as parent. (Markdown files that already have a page ID as Markdown comments are not affected, they retain their existing parent node in Confluence.) If there is no `index.md` or `README.md`, subdirectories inherit the parent page ID.
